config/routes.rb
Wallsome::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resource :user
  resource :verification
  resource :password
  resources :basecamp_users
  resources :basecamp_accounts, :only => [:index]

  scope '/:basecamp_account_name' do
    match 'projects/:project_id/todo_items/dialog', :to => "todo_items#dialog", :as => :todo_item_dialog
    match 'projects/:project_id/todo_lists/dialog', :to => "todo_lists#dialog", :as => :todo_list_dialog
    get 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#edit",
        :as => :edit_project_reorder_todo_lists
    put 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#update",
        :as => :project_reorder_todo_lists

    resources :projects do
      resource :backlog, :only => [:show]
      resources :milestones do
        get 'current', :on => :collection
        resources :todo_lists
      end
      resource :columns, :only => [:edit, :update]
    end

    resources :todo_lists do
      resources :todo_items do
        put :move, :on => :member
      end
    end

    resources :todo_items do
      resources :comments
    end
  end

  # Convenience
  match "/login", :to => "sessions#new", :as => :login
  match "/logout", :to => "sessions#destroy", :as => :logout
  match "/signup", :to => "users#new", :as => :signup
  match "/help", :to => "miscellaneous#help", :as => :help

  match "/subscriptions/activations_notifications",
        :to => "activations_notifications#create",
        :via => :post
  match "/subscriptions/deactivations_notifications",
        :to => "deactivations_notifications#create",
        :via => :post
  match "/subscriptions/failed_notifications",
        :to => "failed_notifications#create",
        :via => :post

  # Temporary workaround
  # TODO: Remove when 37signals update their link to us
  # from beta.wallsome.com to www.wallsome.com
  match "/" => redirect(WALLSOME_SITE_BASE_URL)

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "basecamp_accounts#show"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/basecamp_user.rb
class BasecampUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :basecamp_account

  validates_presence_of :account_name, :message => "Please enter your Basecamp account name"
  validates_format_of   :account_name, :with => /^[a-z0-9-]+$/i, :message => "Please enter a valid Basecamp account name"
  validates_presence_of :api_token, :message => "Please enter your Basecamp api token"
  validates_associated  :basecamp_account
  validates_with BasecampUserValidator, :if => Proc.new { |bu| bu.basecamp_account.present? && bu.api_token.present? }

  after_create :set_basecamp_account_owner_id

  def api_token=(api_token)
    self.encrypted_api_token = api_token_encryptor.encrypt(api_token)
  end

  def api_token
    encrypted_api_token ? api_token_encryptor.decrypt(encrypted_api_token) : ''
  end

  def account_name=(account_name)
    self.basecamp_account = BasecampAccount.find_by_name(account_name)
    self.basecamp_account ||= BasecampAccount.new(:name => account_name)
  end

  def account_name
    basecamp_account.name
  end

  private

    def api_token_encryptor
      @@api_token_encryptor ||= ActiveSupport::MessageEncryptor.new(Wallsome::Application.config.api_token_encryption_secret)
    end

    def set_basecamp_account_owner_id
      if self.basecamp_account.basecamp_users.count == 1
        self.basecamp_account.update_attribute(:owner_id, user_id)
      end
    end

end

app/controllers/basecamp_users_controller.rb
class BasecampUsersController < ApplicationController
  skip_around_filter :set_resource_site_and_user
  skip_around_filter :recover_from_ssl_changes_to_basecamp_accounts
  
  def index
  end
  
  def new
    @basecamp_user = current_user.basecamp_users.build
    @basecamp_user.basecamp_account = BasecampAccount.new
  end
  
  def create
    @basecamp_user = current_user.basecamp_users.build(params[:basecamp_user])
    if @basecamp_user.save
      redirect_to basecamp_users_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @basecamp_user = current_user.basecamp_users.find(params[:id])
  end
  
  def update
    @basecamp_user = current_user.basecamp_users.find(params[:id])
    @basecamp_user.attributes = params[:basecamp_user]
    if @basecamp_user.save
      redirect_to basecamp_users_url
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @basecamp_user = current_user.basecamp_users.find(params[:id])
    @basecamp_user.destroy
    redirect_to basecamp_users_url
  end
end

app/helpers/basecamp_users_helper.rb
module BasecampUsersHelper
end

app/views/basecamp_users/_form.html.erb
<p>
  <%= form.label :account_name, raw("Your Basecamp Account Name") %>
  <%= form.text_field :account_name, :style => "width: 220px;" %> <span>.basecamphq.com</span>
  <%= error_message_on @basecamp_user, :account_name %>
</p>

<p>
  <%= form.label :api_token, raw("API Token <span class=\"hint\">(see 'My info' in Basecamp)</span>") %>
  <%= form.password_field :api_token, :style => "width: 220px;" %>
  <%= error_message_on @basecamp_user, :api_token  %>
</p>

app/views/basecamp_users/edit.html.erb
<% content_for :title do %>
  Edit Basecamp Account
<% end %>
<% content_for :logo do %>
  <h2><%= link_to "Back to Overview", basecamp_accounts_path %></h2>
  <h1>Edit Basecamp Account</h1>
<% end %>

<%= form_for @basecamp_user, :html => { :id => 'account', :style => "width: 360px", :method => :put } do |form| %>
  <%= render :partial => "layouts/flash", :locals => { :flash => flash } %>
  <fieldset>
    <legend>Edit Basecamp Account</legend>
    <%= render :partial => "form", :locals => { :form => form } %>
  </fieldset>
  <fieldset class="buttons">
    <%= link_to "Cancel", basecamp_users_path, :class => "button" %>
    <%= submit_tag 'Update' %>
  </fieldset>
<% end %>

app/views/basecamp_users/index.html.erb
<% content_for :title do %>
  Manage Basecamp Accounts
<% end %>

<% content_for :logo do %>
  <h2><%= link_to "Back to Overview", basecamp_accounts_path %></h2>
  <h1>Manage Basecamp Accounts</h1>
<% end %>

<div class="center-box">
  <%= render :partial => "layouts/flash", :locals => { :flash => flash } %>
  <fieldset>
    <legend>
      Manage Basecamp Accounts
    </legend>
    <%- if current_user.basecamp_users.any? -%>
      <%- current_user.basecamp_users.each do |basecamp_user| -%>
        <p><%= link_to "#{basecamp_user.basecamp_account.name}.basecamphq.com", projects_path(basecamp_user.basecamp_account.name) %> |
           <%= link_to "Edit", edit_basecamp_user_path(basecamp_user) %> |
           <%= link_to "Delete",
                       basecamp_user_path(basecamp_user),
                       :method => :delete,
                       :confirm => "Are you sure you want to delete the Basecamp account?" %>
        </p>
      <%- end -%>
    <%- else -%>
      <%= render :partial => "shared/no_basecamp_account" %>
    <%- end -%>
    <p>
      <%= link_to "+ Add Basecamp Account", new_basecamp_user_path %>
    </p>
  </fieldset>
</div>

app/views/basecamp_users/new.html.erb
<% content_for :title do %>
  Add Basecamp Account
<% end %>

<% content_for :logo do %>
  <h2><%= link_to "Back to Overview", basecamp_accounts_path %></h2>
  <h1>Add Basecamp Account</h1>
<% end %>

<%= form_for @basecamp_user, :html => { :id => 'account', :style => "width: 360px" } do |form| %>
  <fieldset>
    <legend>Add Basecamp Account</legend>
    <%= render :partial => "form", :locals => { :form => form } %>
  </fieldset>
  <fieldset class="buttons">
    <%= link_to "Cancel", :back, :class => "button" %>
    <%= submit_tag 'Create' %>
  </fieldset>
  
  <p>
    Visit <%= link_to "Help/Support", help_path, :target => "_blank" %> if you need help with the setup.
  </p>
<% end %>