config/routes.rb
Wallsome::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resource :user
  resource :verification
  resource :password
  resources :basecamp_users
  resources :basecamp_accounts, :only => [:index]

  scope '/:basecamp_account_name' do
    match 'projects/:project_id/todo_items/dialog', :to => "todo_items#dialog", :as => :todo_item_dialog
    match 'projects/:project_id/todo_lists/dialog', :to => "todo_lists#dialog", :as => :todo_list_dialog
    get 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#edit",
        :as => :edit_project_reorder_todo_lists
    put 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#update",
        :as => :project_reorder_todo_lists

    resources :projects do
      resource :backlog, :only => [:show]
      resources :milestones do
        get 'current', :on => :collection
        resources :todo_lists
      end
      resource :columns, :only => [:edit, :update]
    end

    resources :todo_lists do
      resources :todo_items do
        put :move, :on => :member
      end
    end

    resources :todo_items do
      resources :comments
    end
  end

  # Convenience
  match "/login", :to => "sessions#new", :as => :login
  match "/logout", :to => "sessions#destroy", :as => :logout
  match "/signup", :to => "users#new", :as => :signup
  match "/help", :to => "miscellaneous#help", :as => :help

  match "/subscriptions/activations_notifications",
        :to => "activations_notifications#create",
        :via => :post
  match "/subscriptions/deactivations_notifications",
        :to => "deactivations_notifications#create",
        :via => :post
  match "/subscriptions/failed_notifications",
        :to => "failed_notifications#create",
        :via => :post

  # Temporary workaround
  # TODO: Remove when 37signals update their link to us
  # from beta.wallsome.com to www.wallsome.com
  match "/" => redirect(WALLSOME_SITE_BASE_URL)

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "basecamp_accounts#show"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :basecamp_users, :dependent => :destroy
  has_many :basecamp_accounts, :through => :basecamp_users

  attr_accessor :password, :password_confirmation

  validates_presence_of     :email
  validates_uniqueness_of   :email, :case_sensitive => false
  validates_format_of       :email, :with => %r{.+@.+\..+}

  validates_presence_of     :password, :unless => :password_optional?
  validates_confirmation_of :password, :unless => :password_optional?


  before_create :generate_remember_token

  before_save :initialize_salt,
              :encrypt_password,
              :initialize_verification_token


  def self.authenticate(email, password)
    return nil unless user = find_by_email(email)
    return user if user.authenticated?(password)
  end

  def authenticated?(password)
    encrypted_password == encrypt(password)
  end

  def reset_remember_token!
    generate_remember_token
    save(:validate => false)
  end

  def api_token_for(basecamp_account)
    basecamp_users.where(:basecamp_account_id => basecamp_account.id).first.api_token
  end

  def forgot_password!
    generate_verification_token
    save(:validate => false)
  end

  def update_password(new_password, new_password_confirmation)
    self.password              = new_password
    self.password_confirmation = new_password_confirmation
    if valid?
      self.verification_token = nil
    end
    save
  end

  def confirm_email!
    self.verified           = true
    self.verification_token = nil
    save(:validate => false)
  end

  private

    def password_optional?
      encrypted_password.present? && password.blank?
    end

    def initialize_salt
      if new_record?
        self.salt = generate_hash("--#{Time.now.utc}--#{password}--#{rand}--")
      end
    end

    def encrypt_password
      return if password.blank?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      generate_hash("--#{salt}--#{string}--")
    end

    def generate_hash(string)
      Digest::SHA1.hexdigest(string)
    end

    def generate_remember_token
      self.remember_token = encrypt("--#{Time.now.utc}--#{encrypted_password}--#{id}--#{rand}--")
    end

    def generate_verification_token
      self.verification_token = encrypt("--#{Time.now.utc}--#{password}--")
    end

    def initialize_verification_token
      generate_verification_token if new_record?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :authenticate, :only => [:new, :create]
  skip_around_filter :set_resource_site_and_user
  skip_around_filter :recover_from_ssl_changes_to_basecamp_accounts
  
  before_filter :redirect_to_root, :only => [:new, :create], :if => :signed_in?
  
  layout "logged_out"
  
  def new
    @user = User.new
    @user.basecamp_users.build
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      AccountMailer.verification(@user).deliver
      redirect_to getting_started_url
    else
      render :action => 'new'
    end
  end
  
  def show
    render "show", :layout => "logged_in"
  end
  
  def edit
    current_user.forgot_password!
    redirect_to edit_password_url(:user_id => current_user.id, 
                                  :token => current_user.verification_token)
  end
  
  def destroy
    current_user.delete
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<% content_for :title do %>
  Signup
<% end %>

<%= form_for @user, :url => user_path, :html => { :id => 'account', :style => "width: 360px" } do |form| %>

  <fieldset>
    <legend>Please create a Wallsome Account</legend>
    <p>
      <%= error_message_on @user, :base %>
    </p>
    <p>
      <%= form.label :email, "Your Email Address" %>
      <%= form.text_field :email, :style => "width: 332px;" %>
      <%= error_message_on @user, :email %>
    </p>
    <p>
      <%= form.label :password, "Password" %>
      <%= form.password_field :password, :style => "width: 332px;" %>
      <%= error_message_on @user, :password %>
    </p>
    <p>
      <%= form.label :password_confirmation, "Confirm Password" %>
      <%= form.password_field :password_confirmation, :style => "width: 332px;" %>
      <%= error_message_on @user, :password_confirmation %>
    </p>
  </fieldset>

  <fieldset class="buttons">
    <%= submit_tag 'Create' %>
  </fieldset>
<% end %>

app/views/users/please_verify.html.erb
<div class="center-box">
  You should receive an email from Wallsome shortly.  Please follow the link in the email to verify your account.
</div>

app/views/users/show.html.erb
<% content_for :title do %>
  My Info
<% end %>

<% content_for :logo do %>
  <h2><%= link_to "Back to Overview", basecamp_accounts_path %></h2>
  <h1>My Info</h1>
<% end %>

<div class="center-box">
  <fieldset>
    <legend>My Info</legend>
    <ul>
      <li><%= link_to "Change Password", edit_user_path %></li>
      <li><%= link_to "Manage Basecamp Accounts", basecamp_users_path %></li>
      <li>
        <%= link_to "Delete My Account",
                     user_path,
                     :method => :delete,
                     :confirm => "Are you sure you want to delete your Wallsome account?" %>
      </li>
    </ul>
  </fieldset>
</div>