config/routes.rb
Wallsome::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resource :user
  resource :verification
  resource :password
  resources :basecamp_users
  resources :basecamp_accounts, :only => [:index]

  scope '/:basecamp_account_name' do
    match 'projects/:project_id/todo_items/dialog', :to => "todo_items#dialog", :as => :todo_item_dialog
    match 'projects/:project_id/todo_lists/dialog', :to => "todo_lists#dialog", :as => :todo_list_dialog
    get 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#edit",
        :as => :edit_project_reorder_todo_lists
    put 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#update",
        :as => :project_reorder_todo_lists

    resources :projects do
      resource :backlog, :only => [:show]
      resources :milestones do
        get 'current', :on => :collection
        resources :todo_lists
      end
      resource :columns, :only => [:edit, :update]
    end

    resources :todo_lists do
      resources :todo_items do
        put :move, :on => :member
      end
    end

    resources :todo_items do
      resources :comments
    end
  end

  # Convenience
  match "/login", :to => "sessions#new", :as => :login
  match "/logout", :to => "sessions#destroy", :as => :logout
  match "/signup", :to => "users#new", :as => :signup
  match "/help", :to => "miscellaneous#help", :as => :help

  match "/subscriptions/activations_notifications",
        :to => "activations_notifications#create",
        :via => :post
  match "/subscriptions/deactivations_notifications",
        :to => "deactivations_notifications#create",
        :via => :post
  match "/subscriptions/failed_notifications",
        :to => "failed_notifications#create",
        :via => :post

  # Temporary workaround
  # TODO: Remove when 37signals update their link to us
  # from beta.wallsome.com to www.wallsome.com
  match "/" => redirect(WALLSOME_SITE_BASE_URL)

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "basecamp_accounts#show"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  layout 'project'

  def edit
    @columns = CustomColumn.where(:project_id => current_project.id).order("position").all
  end

  def update
    CustomColumn.order_columns(:project_id         => current_project.id,
                               :ordered_column_ids => params[:ordered_column_ids].split(","))

    redirect_to edit_project_columns_path(:basecamp_account_name => current_account.name, :project_id => current_project.id),
                :notice => "Columns updated"
  end

end

app/views/columns/edit.html.erb
<% content_for :title do %>
  <%= current_project.name %> &gt; Columns
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag "todo_lists", "todo_items", "comments", :cache => "wall" %>

  <script type="text/javascript" charset="utf-8">
    app.responsiblePartyMap = <%= raw responsible_party_id_to_display_name.to_json %>;
    app.basecampAccountName = '<%= current_account.name %>';
  </script>
<% end %>

<% content_for :logo do %>
  <%= current_project.name %>
<% end %>

<div id="workspace_header">
  <div id="workspace_header_wrapper">
    <div id="title_and_links">
      <h1>Manage Columns for Entire Project: <%= current_project.name %></h1>
      <div id="workspace_header_links">
      </div>
    </div>

    <div id="workspace_header_buttons">
    </div>
  </div>
</div>

<%= form_tag(project_columns_path(:project_id => current_project.id),
             :method => "put",
             :class => "manage_columns") do %>
  <%= render :partial => "layouts/flash", :locals => { :flash => flash } %>
  <h3 style="margin-left: 65px; font-size:18px;">Manage Columns</h3>
  <ul id="manage_columns">
    <li class="column not_sortable">Open</li>
    <% @columns.each do |column| %>
      <%= content_tag(:li,
                      :class    => "column sortable",
                      "data-id" => column.id) do %>
        <%= column.name %>
        <a href="#" class="delete" style="float: right; text-align: right;">Delete</a>
      <% end %>
    <% end %>
    <li class="column not_sortable">Completed</li>
  </ul>
  <%= hidden_field_tag :ordered_column_ids %>
  <fieldset class="buttons">
    <p style="margin-right: 60px;">
      <%= link_to "+ New Column",
                  "#",
                  :id    => "new_column",
                  :class => "button" %>
      <%= submit_tag "Done", :id => "submit_update_columns" %>
    </p>
  </fieldset>
<% end %>

<script type="text/javascript" charset="utf-8">//<![CDATA[
  $(function() {
    $("#manage_columns").sortable({
      containment: 'parent',
      items: 'li.sortable',
      opacity: 0.8,
      tolerance: 'pointer'
    }).disableSelection();

    $("#new_column").click(function(event) {
      var name = prompt("Enter new column name", ""),
      element = $("<li class='column sortable'></li>");
      element.attr("data-id", name);
      element.html(name + "<a href='#' class='delete' style='float:right; text-align: right;'>Delete</a>");
      $("#manage_columns li.sortable").last().after(element);
    });

    $("#submit_update_columns").click(function(event) {
      var orderedIds = $.makeArray(getColumnIds($("#manage_columns")));
      app.spinner.dialog('open');
      $("#ordered_column_ids").val(orderedIds);
    });

    $("#manage_columns .delete").click(function() {
      $(this).closest("li").remove();
    });


    getColumnIds = function(unorderedList) {
      var ids = unorderedList.find("li.sortable").map(function() {
        return $(this).attr("data-id");
      });
      return ids;
    };

  });
//]]></script>