config/routes.rb
Wallsome::Application.routes.draw do
  resource :session, :only => [:new, :create, :destroy]
  resource :user
  resource :verification
  resource :password
  resources :basecamp_users
  resources :basecamp_accounts, :only => [:index]

  scope '/:basecamp_account_name' do
    match 'projects/:project_id/todo_items/dialog', :to => "todo_items#dialog", :as => :todo_item_dialog
    match 'projects/:project_id/todo_lists/dialog', :to => "todo_lists#dialog", :as => :todo_list_dialog
    get 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#edit",
        :as => :edit_project_reorder_todo_lists
    put 'projects/:project_id/todo_lists/reorder',
        :to => "reorder_todo_lists#update",
        :as => :project_reorder_todo_lists

    resources :projects do
      resource :backlog, :only => [:show]
      resources :milestones do
        get 'current', :on => :collection
        resources :todo_lists
      end
      resource :columns, :only => [:edit, :update]
    end

    resources :todo_lists do
      resources :todo_items do
        put :move, :on => :member
      end
    end

    resources :todo_items do
      resources :comments
    end
  end

  # Convenience
  match "/login", :to => "sessions#new", :as => :login
  match "/logout", :to => "sessions#destroy", :as => :logout
  match "/signup", :to => "users#new", :as => :signup
  match "/help", :to => "miscellaneous#help", :as => :help

  match "/subscriptions/activations_notifications",
        :to => "activations_notifications#create",
        :via => :post
  match "/subscriptions/deactivations_notifications",
        :to => "deactivations_notifications#create",
        :via => :post
  match "/subscriptions/failed_notifications",
        :to => "failed_notifications#create",
        :via => :post

  # Temporary workaround
  # TODO: Remove when 37signals update their link to us
  # from beta.wallsome.com to www.wallsome.com
  match "/" => redirect(WALLSOME_SITE_BASE_URL)

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "basecamp_accounts#show"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  layout 'project'
  
  def show
    @filter = (params[:filter] || "unassigned").to_sym
    @todo_lists_json = todo_lists_as_json(if @filter == :all
      current_project.todo_lists
    elsif @filter == :uncompleted
      current_project.todo_lists(:uncompleted)
    else
      current_project.todo_lists(:unassigned)
    end)
  end
end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/views/backlogs/_todo_list.html.erb
<%- if list.new? -%>
<div id="template_todo_list" class="todo_list" style="display:none;">
<%- else -%>
<div id="todo_list_<%= list.id %>" class="todo_list">
<% end %>
  <div class="todo_list_name">
    <h3 title="<%= list.description %>"><%= list.name %></h3>
    <%- if completed -%>
      <span class="completed">Completed</span>
    <%- end -%>
    <span class="todo_list_actions">
      <%= link_to "Edit", "#", :class => "edit_todo_list" %> |
      <%= link_to "Delete", "#", :class => "delete_todo_list" %> |
      <%= link_to "Open in Basecamp", current_account.url + "projects/#{current_project.id}/todo_lists/#{list.id}", :class => "go_to_basecamp" %>
    </span>

    <span data-milestone-id="<%= list.milestone_id %>" class="milestone_title" style="float:right;" title="<%= list.milestone.try(:title) %>">
      <%= truncate(list.milestone.try(:title), :length => 40) %>
    </span>
  </div>
</div>

app/views/backlogs/_todo_list_links.html.erb
<%= link_to "+ To-do List", 
            "#",
            :class => "button",
            :id => "new_todo_list" %>

<div style="float: left; margin: 3px 10px;">
  <form class="inline">
    Filter
    <%= radio_button_tag "filter", "unassigned", @filter == :unassigned, :class => "filter" %>
    <%= label_tag "filter_unassigned", "Unassigned", :style => "display: inline;" %>
    <%= radio_button_tag "filter", "uncompleted", @filter == :uncompleted, :class => "filter" %>
    <%= label_tag "filter_uncompleted", "Uncompleted", :style => "display: inline;" %>
    <%= radio_button_tag "filter", "all", @filter == :all, :class => "filter" %>
    <%= label_tag "filter_all", "All", :style => "display: inline;" %>
  </form>
</div>

<%= link_to "Reorder Lists", 
            edit_project_reorder_todo_lists_path(:project_id => current_project.id, :filter => @filter),
            :class => "button",
            :style => "float:right; margin: 0px 19px 8px 8px;" %>

app/views/backlogs/show.html.erb
<% content_for :title do %>
  <%= current_project.name %> &gt; Backlog
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag "todo_lists", "todo_items", "comments", :cache => "wall" %>
  <%= javascript_include_tag "backlogs" %>

  <script type="text/javascript" charset="utf-8">
    app.responsiblePartyMap = <%= raw responsible_party_id_to_display_name.to_json %>;
    app.basecampAccountName = '<%= current_account.name %>';
  </script>
<% end %>

<% content_for :logo do %>
  <%= current_project.name %>
<% end %>

<div id="workspace_header">
  <div id="workspace_header_wrapper">
    <div id="title_and_links">
      <h1>Backlog</h1>
      <div id="workspace_header_links">
        <form class="inline">
          Filter
          <%= radio_button_tag "filter", "unassigned", @filter == :unassigned, :class => "filter" %>
          <%= label_tag "filter_unassigned", "Unassigned", :style => "display: inline;" %>
          <%= radio_button_tag "filter", "uncompleted", @filter == :uncompleted, :class => "filter" %>
          <%= label_tag "filter_uncompleted", "Uncompleted", :style => "display: inline;" %>
          <%= radio_button_tag "filter", "all", @filter == :all, :class => "filter" %>
          <%= label_tag "filter_all", "All", :style => "display: inline;" %>
        </form>
      </div>
    </div>

    <div id="workspace_header_buttons">
      <%= link_to "+ To-do List",
                  "#",
                  :class => "button",
                  :id => "new_todo_list" %>

      <%= link_to "Reorder Lists",
                  edit_project_reorder_todo_lists_path(:project_id => current_project.id, :filter => @filter),
                  :class => "button spinner" %>
    </div>
  </div>
</div>

<%= render :partial => 'todo_list', :locals => { :list => TodoList.new, :completed => false } %>

<%= javascript_include_tag "lib/json2.js",
                           "lib/underscore.js",
                           "lib/backbone.js",
                           "lib/ICanHaz.js",
                           "config.js", :cache => "backbone-lib" %>

<script id="backlog_todo_list" type="text/html">
  <div class="todo_list_name">
    <h3 title="{{ description }}">{{ name }}</h3>
    <span class="todo_list_actions">
      <a href="#" class="edit_todo_list">Edit</a> |
      <a href="#" class="delete_todo_list">Delete</a> |
      <a href="<%= current_account.url + 'projects/{{ project_id }}/todo_lists/{{ id }}' %>" class="go_to_basecamp">Open in Basecamp</a>
    </span>
    <span data-milestone-id="{{ milestone_id }}" class="milestone_title" style="float:right; display:none;" title="{{ milestone_title }}">
      {{ milestone_title }}
    </span>

  </div>
</script>

<%= javascript_include_tag "app.js",
                           "routers/wall_router.js",
                           "routers/backlog_router.js",
                           "models/todo_item.js",
                           "models/todo_list.js",
                           "models/milestone.js",
                           "models/project.js",
                           "collections/todo_items.js",
                           "collections/todo_lists.js",
                           "views/backlog_todo_list.js",
                           "views/todo_list.js",
                           "views/todo_list_column.js",
                           "views/todo_item.js", :cache => "backbone-app" %>

<script type="text/javascript" charset="utf-8">//<![CDATA[
  <% todo_list_dialog_params = {
       :project_id => current_project.id,
       :basecamp_account_name => current_account.name } %>
  $.get("<%= todo_list_dialog_path(todo_list_dialog_params) %>", function(data) {
    $("#workspace").append(data);
  });

  $(function() {
    var todoLists = <%=raw @todo_lists_json %>;
    wallsome.App.backlogInit(todoLists);

    <% if @filter == :unassigned %>
      var showMilestoneSelector = false,
          keepTodoListWithDifferentMilestone = false;
    <% else %>
      var showMilestoneSelector = true,
          keepTodoListWithDifferentMilestone = true;
    <% end %>
    app.TodoListMethods.newTodoListLinkBehavior($("#new_todo_list"), showMilestoneSelector);
    app.TodoListMethods.editTodoListBehavior($(".edit_todo_list"), keepTodoListWithDifferentMilestone);
    app.TodoListMethods.deleteTodoListBehavior($(".delete_todo_list"));
  });
//]]></script>